# Generated by Django 5.0.1 on 2024-02-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestant",
            name="created_year",
            field=models.IntegerField(default=2024),
        ),
    ]
