# Generated by Django 5.0.1 on 2024-02-04 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_contestant_created_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadvideo",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 4, 19, 51, 52, 864643, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
