# Generated by Django 5.0.1 on 2024-02-04 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_uploadvideo_upload_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadvideo",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 4, 19, 54, 2, 338426, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
