# Generated by Django 5.0.1 on 2024-02-04 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_uploadvideo_upload_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadvideo",
            name="upload_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
