# Generated by Django 5.0.1 on 2024-02-05 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_uploadvideo_upload_time"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Header",
            new_name="HeaderImage",
        ),
    ]
