# Generated by Django 5.0.7 on 2024-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_performance"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedialinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.URLField(unique=True)),
                ("twitter", models.URLField(unique=True)),
                ("whatsapp", models.URLField(unique=True)),
                ("tiktok", models.URLField(unique=True)),
            ],
        ),
    ]
