# Generated by Django 5.0.7 on 2024-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_socialmedialinks"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitedArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("image", models.ImageField(upload_to="invited_artist")),
                ("short_content", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="socialmedialinks",
            old_name="twitter",
            new_name="instagram",
        ),
    ]
